name: GNLP
favicon: null
layout_spectrum: 0.2089129127562046
typography_spectrum: 0.5658227095846087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.12552240188233554
  lightness: 0.7627854645252228
  saturation: 0.16056052432395518
  rhythmicContrast: 0.9972610417753458
purpose: []
